config/routes.rb
Fmypclife::Application.routes.draw do

  resources :posts do
    collection do
      post :sms
      get :data
      get :search
      get :popular
      get :rating
    end
    member do
      put :upvote
      put :downvote
    end
  end

  devise_for :users

  match '/glossary', :to => 'statics#glossary', :as => :glossary
  match '/contribute', :to => 'statics#contribute', :as => :contribute
  match '/disclaimer', :to => 'statics#disclaimer', :as => :disclaimer

  root :to => 'posts#new'

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :body, :length => { :maximum => 255 }, :uniqueness => true, :presence => true

  default_scope :order => 'created_at DESC'
  scope :most_popular, order('popularity DESC')
  scope :highly_rated, order('rating DESC')

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    @posts = @posts.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end
 
  # GET /posts/popular
  def popular
    @posts = @posts.unscoped.order("popularity DESC").paginate(:page => params[:page], :per_page => 20)
    @message = "These are the posts which have inspired the most up- and down-voting. Love it or hate it, everyone seems to have something to say..."

    respond_to do |format|
      format.html { render 'index' }
    end
  end

  # GET /posts/rating
  def rating
    @posts = @posts.unscoped.order("rating #{params[:sort]}").paginate(:page => params[:page], :per_page => 20)
    if params[:sort] == 'DESC'
      @message = "These posts have aroused everyone's sympathy."
    else
      @message = "Wow. Take a look at the posts which have made our readers most upset."
    end

    respond_to do |format|
      format.html { render 'index' }
    end
  end

  # GET /posts/search
  def search
    @query = "%" + (params[:query] ||= '') + "%"
    @posts = Post.where("body LIKE ?", @query).paginate(:page => params[:page], :per_page => 20)
    @message = "Your search for '#{params[:query] ||= ''}' returned #{@posts.count} result#{@posts.count == 1 ? nil : 's'}."
    render 'index'
  end

  # GET /posts.json
  def data
    @posts = Post.all

    if params[:style] == 'count'
      render 'count'
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @posts = Post.accessible_by(current_ability).paginate(:page => params[:page], :per_page => 10)
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post].merge(:ip => request.remote_ip))

    respond_to do |format|
      if (user_signed_in? || gotcha_valid?) && @post.save
        Pusher['posts_channel'].trigger('new_post', {
          :id => @post.id,
          :body => @post.body,
          :country => @post.country
        })
        format.html { redirect_to root_path, notice: 'Thanks for contributing!' }
        format.json { render json: @post, status: :created, location: @post }
        format.js
      else
        @posts = Post.accessible_by(current_ability).paginate(:page => params[:page], :per_page => 20)
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # POST /posts/sms
  # Moonshado SMS input
  def sms
    @post = Post.new(
      :body => params[:message],
      :ip => params[:device_address],
      :contry => 'Unknown'
    )
    if @post.save
      Pusher['posts_channel'].trigger('new_post', {
        :id => @post.id,
        :body => @post.body,
        :country => @post.country
      })
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1/upvote
  def upvote
    @post = Post.find(params[:id])
    
    respond_to do |format|
      if @post.increment!(:upvotes)
        @post.update_attributes(:popularity => @post.upvotes + @post.downvotes, :rating => @post.upvotes - @post.downvotes)
        format.js
        format.html { redirect_to new_post_path, notice: 'Your vote was cast!' }
      else
        @posts = Post.accessible_by(current_ability).paginate(:page => params[:page], :per_page => 20)
        format.js
        format.html { render action: 'new', notice: 'Your vote could not be cast.' }
      end
    end
  end

  # PUT /posts/1/downvote
  def downvote
    @post = Post.find(params[:id])
    
    respond_to do |format|
      if @post.increment!(:downvotes)
        @post.update_attributes(:popularity => @post.upvotes + @post.downvotes, :rating => @post.upvotes - @post.downvotes)
        format.js
        format.html { redirect_to new_post_path, notice: 'Your vote was cast!' }
      else
        @posts = Post.accessible_by(current_ability).paginate(:page => params[:page], :per_page => 20)
        format.js
        format.html { render action: 'new', notice: 'Your vote could not be cast.' }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to new_post_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= bootstrap_form_for @post, :remote => true do |f|
  = f.text_area :body, :class => 'span4', :rows => 6, :maxlength => '255', :help_inline => '255 chars max', :label => 'Share your FMPCL moment! Today...FMPCL!'
  = f.select :country, pc_countries, :class => 'span4', :label => 'Your country of service'
  - unless user_signed_in?
    .control-group
      = gotcha :gotcha_type => :sum, :label_options => { :class => 'control-label' }
      %span.help_inline{:rel => 'popover-top', :title => "What's with this?", 'data-content' => "This is a CAPTCHA, designed to stop non-humans from posting. I know, it's very unfair."}
        %strong &nbsp;?
      %p.help-block I hate math! I'd rather #{link_to 'sign up', new_user_registration_path}!
  = f.submit :value => 'Post it now!', :disable_with => 'posting now...', :class => 'btn btn-primary'

app/views/posts/_post.html.haml
%blockquote.post{:id => post.id}
  = button_to raw('&times;'), post, :method => :delete, :class => 'close' if can? :destroy, post
  %p
    = post.body
  %h4
    = post.country
    %small
      = time_ago_in_words(post.created_at)
      ago
      &nbsp;
      &nbsp;
      = link_to post do
        view
        &rarr;
  .btn-group
    = link_to post.upvotes, rating_posts_path(:sort => 'DESC'), :class => 'btn btn-mini btn-success upvote_count'
    = link_to 'Yep, that sucks!', upvote_post_path(post), :method => :put, :class => 'btn btn-mini', :remote => true
  .btn-group
    = link_to post.downvotes, rating_posts_path(:sort => 'ASC'), :class => 'btn btn-mini btn-danger downvote_count'
    = link_to "FMPCL, really?", downvote_post_path(post), :method => :put, :class => 'btn btn-mini', :remote => true
  :erb
    <div class="fb-like" data-href="<%= post_url(post) %>?utm_source=Facebook&utm_medium=online&utm_campaign=Facebook%2BIndividual%2BLike%2BButtons" data-send="true" data-layout="button_count" data-width="90" data-show-faces="true" data-font="arial"></div>
%hr.clear-both

app/views/posts/create.js.erb
<% if !user_signed_in? && !gotcha_valid? %>
  $('form#new_post').prepend('Oh dear. Check your math.');
<% elsif @post.errors.any? %>
  $('form#new_post').prepend("Uh oh. Is your post blank, or a duplicate?");
<% else %>
  // $('#posts_feed').prepend("<%= escape_javascript(render(@post))%>");
  $('#post_body').val('');
  $('#post_country').val('');
  //alert('test');
<% end %>

app/views/posts/downvote.js.erb
$(function(){
  $('blockquote.post#<%= @post.id %> a.downvote_count').html(<%= @post.downvotes %>);
});

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
.row
  .span11
    .hero-unit
      = link_to 'Share it now!', new_post_path, :class => 'btn btn-large btn-primary float-right'
      %h1 Know something funny?
      %p It's never too late to share your shame! Trust us, everyone else will enjoy it.
    %h3= @message ||= 'Already shared? Welcome to the archives. Enjoy yourself.'
    %hr
.row
  .span4
    = render @posts.values_at(* @posts.each_index.select {|i| i.even?})
    &nbsp;
  .span4
    = render @posts.values_at(* @posts.each_index.select {|i| i.odd?})
    &nbsp;
  .span2.offset1
    - 2.times do
      = render 'shared/adsense_v'
.row
  .span11
    = will_paginate :class => 'pagination pagination-centered'

app/views/posts/new.html.haml
.row
  .span11
    .hero-unit
      = link_to 'Share something now!', '#post_it_now', :class => 'float-right btn btn-large btn-success'
      %h1 F*** My Peace Corps Life.
      %p
        Some days, all you can do is laugh.
      :erb
        <div class="fb-like" data-href="http://bit.ly/IUaU2b" data-send="true" data-width="450" data-show-faces="false" data-font="arial"></div>
.row
  .span2
    - if can? :manage, Post
      .hero-unit
        %p.center Posts
        %h1.center= Post.count
      .hero-unit
        %p.center Users
        %h1.center= User.count
    - 3.times do
      = render 'shared/adsense_v'
  .span4
    #posts_feed
      = render @posts
  .span5
    .alert.alert-block.alert-success
      %h4 Hey you! Yeah, you!
      %p Share an FMPCL moment, whether your COS date is 20 years past or 2 away! It's never too late!
    .well#post_it_now
      = render 'form'
    - ip_hash = request.remote_ip.split('.')
    - if ip_hash[0].to_i == 41
      - if ip_hash[1].to_i == 82
        -if 63 < ip_hash[2].to_i && ip_hash[2].to_i < 170
          - country = 'Senegal'
    - if country
      .alert.alert-block.alert-success
        %h4.alert-heading Text us from the vil!
        %p Hey, it looks like you're in #{country}! Send a text/SMS to <strong>77 750 7234</strong> and it'll show up here! Cool!
    - else
      .alert.alert-block.alert-info
        %p Sorry, but we don't currently have SMS service in your country. Want it? #{link_to 'Find out how', contribute_path}.
    -#.alert.alert-block.alert-info
      %h3.center
        We're here, and we're listening! Stay tuned for feedback/ratings in the next 48 hours... Meanwhile, please direct all site feedback to involve@fmpcl.com.
    .alert.alert-block.alert-warning
      %h4.center
        This site is a place for humor and sharing; if you don't like it, please refrain from attacking those who choose to participate. For more info, read the #{link_to 'disclaimer', disclaimer_path}.
    %h2 What's with this site?
    %p Don't things happen to you every now and then as PCVs that are just too weird, uncomfortable, or unbelievable to not share? The two of us behind this site served in West Africa, and we'd like to hear all of your FMPCL moments. Share away!
    %h2 Confused?
    %p Check out the #{link_to 'glossary', glossary_path} if you're finding any tricky acronyms or veiled speech.
    %h2 Do I need an account?
    %p Absolutely not! Just solve the basic math and post away! If you want to avoid the math (we can't blame you) go ahead and create an account. We don't ask for (or want) your name, location or phone number. All you need is an email with which to authenticate yourself.
.row
  .span8.offset2
    = will_paginate :class => 'pagination pagination-centered'

app/views/posts/show.html.haml
.row
  .span11
    .hero-unit
      %span.float-right
        = link_to 'leave your own', new_post_path, :class => 'btn btn-large btn-primary'
        = link_to 'read them all', posts_path, :class => 'btn btn-large btn-success'
      %h1 Does this make you laugh? Cry?
      %span.clearfloat &nbsp;
.row
  .span2
    = render 'shared/adsense_v'
  .span4.offset1
    = render @post
    %h1 Also try...
    %hr
    = render Post.offset(Post.count / 2).limit(2).all
  .span2
    = render 'shared/adsense_v'
  .span2
    = render 'shared/adsense_v'

app/views/posts/upvote.js.erb
$(function(){
  $('blockquote.post#<%= @post.id %> a.upvote_count').html(<%= @post.upvotes %>);
});