config/routes.rb
Fmypclife::Application.routes.draw do

  resources :posts do
    collection do
      post :sms
      get :data
      get :search
      get :popular
      get :rating
    end
    member do
      put :upvote
      put :downvote
    end
  end

  devise_for :users

  match '/glossary', :to => 'statics#glossary', :as => :glossary
  match '/contribute', :to => 'statics#contribute', :as => :contribute
  match '/disclaimer', :to => 'statics#disclaimer', :as => :disclaimer

  root :to => 'posts#new'

end

app/views/layouts/application.html.haml
:erb
  <!DOCTYPE html>
%html
  %head
    %title F*** My Peace Corps Life | Tales of wit and woe from PCVs
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    :erb
      <script src="http://js.pusher.com/1.11/pusher.min.js"></script>
      <script type="text/javascript">
        var pusher = new Pusher('<%= Pusher.key %>'); // uses your API KEY
        var channel = pusher.subscribe('posts_channel');
        channel.bind('new_post', function(data) {
           //alert(data.body);
           $('#posts_feed').prepend('<blockquote class="blockquote-warning"><p>' + data.body + '</p><h4>' + data.country + '<small>just posted!</small></h4><hr/>').hide().slideDown(3000);
           $('#new_post_notification').slideUp().remove();
           $('#alerts').prepend('<div id="new_post_notification" class="alert center">New post!</div>');
        });
      </script>
    = csrf_meta_tags
    - if Rails.env.production?
      :erb
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-31294386-1']);
          _gaq.push(['_setDomainName', '<%= request.domain %>']);
          _gaq.push(['_setAllowLinker', true]);
          _gaq.push(['_trackPageview']);
          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
  %body
    :erb
      <div id="fb-root"></div>
      <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    .container
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            .row
              .span11
                %a.brand{:href => '/'} F*** My PC Life
                %ul.nav#main_topnav_ul
                  %li= link_to 'Archives', posts_path if can? :read, Post
                  %li= link_to 'Popular', popular_posts_path if can? :read, Post
                  %li= link_to 'Loved', rating_posts_path(:sort => 'DESC') if can? :read, Post
                  %li= link_to 'Loathed', rating_posts_path(:sort => 'ASC') if can? :read, Post
                = form_tag search_posts_path, :method => :get, :class => 'navbar-search pull-left' do
                  = text_field_tag 'query', nil, :class => 'search-query', 'placeholder' => 'search FMPCLs'
                %ul.nav.pull-right
                  %li.dropdown
                    %a.dropdown-toggle{:href => '#', 'data-toggle' => 'dropdown'}
                      = user_signed_in? ? 'Sign out' : 'Sign in'
                      %b.caret
                    %ul.dropdown-menu
                      - if user_signed_in?
                        %li= link_to "Sign out #{current_user.email}", destroy_user_session_path, :method => :delete if user_signed_in?
                      - else
                        %li= link_to 'Sign in', new_user_session_path unless user_signed_in?
                        %li= link_to 'Sign up', new_user_registration_path unless user_signed_in?
      .row
        .span5.offset3#alerts
          - if notice
            .alert.alert-success.center= notice
          - if alert
            .alert.alert-error.center= alert
      = yield
      .row
        .span8.offset2
          %hr
          %p.center
            This service has been brought to you by the struggles and suffering of #{link_to 'Peace Corps', 'http://peacecorps.gov'} Volunteers worldwide. Lucky them.
            %br
            #{link_to 'archives', posts_path} | #{link_to 'glossary', glossary_path} | #{link_to 'disclaimer', disclaimer_path} | #{link_to 'contribute', contribute_path}
          = debug(params) if Rails.env.development?